version: '3.8'

services:
  rosbot:
    build: .
    container_name: rosbot
    stop_signal: SIGINT
    network_mode: host
    privileged: true
    devices:
      - /dev/video0:/dev/video0
      - /dev/ttyUSB0:/dev/ttyUSB0 # For LiDAR or other serial devices, adjust as needed
      - /dev/gpiomem:/dev/gpiomem
      - /dev/input/js0:/dev/input/js0
      - /dev/input/event5:/dev/input/event5
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    command: bash -c "source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch robocamp_rosbot bringup.launch.py"

  ds4_driver:
      build: .
      container_name: ds4_driver
      stop_signal: SIGINT
      network_mode: host
      privileged: true
      devices:
        - /dev:/dev
      volumes:
        - /dev:/dev
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /opt/underlay_ws/src/ds4_drive:/opt/underlay_ws/src/ds4_driver
      environment:
        - naomiz/ds4_driver:humble
        - DISPLAY=${DISPLAY}
        - QT_X11_NO_MITSHM=1
      command: bash -c "colcon build && bash -i"