version: '3.8'

services:
  rosbot:
    build: .
    container_name: rosbot
    network_mode: host
    privileged: true
    devices:
      - /dev/video0:/dev/video0
      - /dev/ttyUSB0:/dev/ttyUSB0 # For LiDAR or other serial devices, adjust as needed
      - /dev/gpiomem:/dev/gpiomem
      - /dev/input/js0:/dev/input/js0
      - /dev/input/event5:/dev/input/event5
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    command: bash -c "source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch robocamp_rosbot bringup.launch.py"
